# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192N6VSFX5-GGz5pobPYR3LyfQlQOBJQd
"""

#Apresentaçao

nome=input('Insira seu nome')
print('Seja bem vindo,',nome,'essa é uma calculadora basica,ela tem esse nome pelo fato de limitar a contas apenas de soma ,subtraçao , multiplicaçao e divisao.')

#Base da calculadora

def ler_numeros(mensagem):

  while True:
      try:
          numero = float(input(mensagem))
          return numero
      except ValueError:
          print('Apenas numeros,pfv')


#Calculadora

while True:
    print('Calcualdora Basica')
    print('1 - Soma')
    print('2 - Substraçao')
    print('3 - Multiplicaçao')
    print('4 - Divisao')
    print('5 - Encerrar operaçoes')

    opcao= input('Escolha uma opcao')

    if opcao == '5':
        print('Operaçoes encerradas,obrigado')
        break

    if opcao not in ['1','2','3','4','5']:
        print('Digite apenas as opcoes disponiveis')
        continue

    primeiro_numero= ler_numeros('Ensira o primeiro numero')
    segundo_numero= ler_numeros('Ensira o segundo numero')

    if opcao == '1':
        resultado = primeiro_numero + segundo_numero
        print(f'Resultado: {resultado}')

    elif opcao == '2':
      resultado = primeiro_numero - segundo_numero
      print(f'Resultado: {resultado}')

    elif opcao == '3':
      resultado = primeiro_numero * segundo_numero
      print(f'Resultado: {resultado}')

    elif opcao == '4':

     if segundo_numero == 0:
        print('Erro!Não é possivel dividir por zero')

     else:
      resultado = primeiro_numero / segundo_numero
      print(f'Resultado: {resultado}')

#FIM